echo Starting Laravel server...
start cmd /k php artisan serve --host=0.0.0.0 --port=8000

echo Starting Laravel Reverb...
start cmd /k php artisan reverb:start --host=0.0.0.0 --port=8080

echo Building frontend...
start cmd /k npm run build